name: PHP Workflow

on:
  push:
    branches: [moje_pliki]
  pull_request:
    branches: [moje_pliki]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Sprawdź wersję PHP
      run: php -v

    - name: (opcjonalnie) Uruchom plik PHP
      run: |
        echo "<?php echo 'Działa PHP!';" > test.php
        php test.php
